export const RENDER_FILM_CARD = "RENDER_FILM_CARD";
export const RENDER_NOWSHOWING_FILM = "RENDER_NOWSHOWING_FILM";
export const RENDER_COMINGSOON_FILM = "RENDER_COMINGSOON_FILM";
export const RENDER_FILM_INFO = "RENDER_FILM_INFO";
