export const LOGIN_ACTION = "LOGIN_ACTION";
export const RENDER_USER_LIST = "RENDER_USER_LIST";
export const RENDER_USER_INFO = "RENDER_USER_INFO";
export const SET_BOOKING_HISTORY = "SET_BOOKING_HISTORY";
