export const RENDER_CINEMAROOM_DETAIL = "RENDER_CINEMAROOM_DETAIL";
export const SELECT_SEAT = "BSELECT_SEAT";
export const BOOK_TICKET = "BOOK_TICKET";
export const CANCEL_BOOKING = "CANCEL_BOOKING";
export const CHANGE_TAB = "CHANGE_TAB";
export const CHANGE_TAB_ACTIVE = "CHANGE_TAB_ACTIVE";
