export const RENDER_CINEMAROOM_DETAIL = "RENDER_CINEMAROOM_DETAIL";
export const SELECT_SEAT = "BSELECT_SEAT";
export const BOOK_TICKET = "BOOK_TICKET";
export const CANCEL_BOOKING = "CANCEL_BOOKING";
